// syntax = "proto3";
// package ems.v1;

// import "google/api/annotations.proto";
// import "ems/v1/genesis.proto";

// option go_package = "github.com/rollchains/hackmoschain/x/ems/types";

// // Query provides defines the gRPC querier service.
// service Query {
//   // Params queries all parameters of the module.
//   rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
//     option (google.api.http).get = "/ems/v1/params";
//   }

//   // rpc GetEvent(QueryGetEventRequest) returns (QueryGetEventResponse) {
//   //   option (google.api.http).get = "/ems/v1/name/{organizer}";
//   // }

//   rpc GetEvent(QueryGetEventRequest) returns (QueryGetEventResponse) {
//     option (google.api.http).get = "/ems/v1/event/{name}";
//   }
// }

// // QueryParamsRequest is the request type for the Query/Params RPC method.
// message QueryParamsRequest {}

// // QueryParamsResponse is the response type for the Query/Params RPC method.
// message QueryParamsResponse {
//   // params defines the parameters of the module.
//   Params params = 1;
// }

// message QueryGetEventRequest {
//   // string organizer = 1;
//   string name = 1;
// }

// message QueryGetEventResponse {
//   //   string name = 1;
//   string organizer = 1;
//   string name = 2;
//   string description = 3;
//   string location = 4;
//   string date = 5;
//   string time = 6;
//   string ticket_price = 7;
//   uint64 num_tickets = 8;
//   repeated string ticket_categories = 9;
// }

// proto/ems/v1/query.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: ems/v1/query.proto

package emsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName   = "/ems.v1.Query/Params"
	Query_GetEvent_FullMethodName = "/ems.v1.Query/GetEvent"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	GetEvent(ctx context.Context, in *QueryGetEventRequest, opts ...grpc.CallOption) (*QueryGetEventResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetEvent(ctx context.Context, in *QueryGetEventRequest, opts ...grpc.CallOption) (*QueryGetEventResponse, error) {
	out := new(QueryGetEventResponse)
	err := c.cc.Invoke(ctx, Query_GetEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	GetEvent(context.Context, *QueryGetEventRequest) (*QueryGetEventResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) GetEvent(context.Context, *QueryGetEventRequest) (*QueryGetEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetEvent(ctx, req.(*QueryGetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ems.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _Query_GetEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ems/v1/query.proto",
}
